### ISSUE TITLE
Installation Script Failure Ubuntu

### ISSUE THREAD

**Issue by thehoodbuddha** [afmurillo/DHALSIM#15]
Hi, 

I am trying to run DHALSIM on my virtual machine. For the installation I utilise the installation script which fails. 
System Version: ```Ubuntu 20.04.3 LTS```

After installing using the ```install.sh``` I run the code as stated at the end of the script. However, I receive the following output:

```Traceback (most recent call last):
  File "./dhalsim", line 33, in <module>
    sys.exit(load_entry_point('dhalsim', 'console_scripts', 'dhalsim')())
  File "./dhalsim", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: dhalsim
```

Based on this I run the setup.py manually and try to rerun DHALSIM by: 

```sudo dhalsim examples/ctown_topology/ctown_config.yaml```

Result:

```Traceback (most recent call last):
  File "/usr/local/bin/dhalsim", line 11, in <module>
    load_entry_point('dhalsim==1.1.0', 'console_scripts', 'dhalsim')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/dhalsim-1.1.0-py3.8.egg/dhalsim/command_line.py", line 12, in <module>
    from dhalsim.parser.config_parser import ConfigParser
ModuleNotFoundError: No module named 'dhalsim.parser'
```
Maybe I am doing something wrong here. However, I followed the installation documentation.

**Comment by afmurillo** [comment]
Helllo, 
I will take a look into this next week, I was on holiday break.

**Comment by thehoodbuddha** [comment]
Hi, 

Thank you! If you need any additional information or help, send me a message.

**Comment by afmurillo** [comment]
Hi,

I just ran the installation script on a new virtual machine, using the master branch and the script ran and installed DHALSIM with no issues. Perhaps there is a conflict with some package in your environment. Is there a way you can send me by DM the ouput of "pip freeze" both for Python2 and Pyhton3? Thank you

**Comment by thehoodbuddha** [comment]
Hi, 

I am not sure how to DM you directly? May I use your email in the published research paper? _Co-Simulating Physical Processes and Network Data for High-Fidelity Cyber-Security Experiments_

**Comment by afmurillo** [comment]
Hello, yes please feel free to write to me to my email

**Comment by thehoodbuddha** [comment]
Installation is successful with the new pushed updates.  Maybe include a test command in the documentation to verify that all components work accordingly.
