### ISSUE TITLE
aarch64 support for libepanet.so

### ISSUE THREAD

**Issue by MuratCaganGogebakan** [afmurillo/DHALSIM#29]
I am trying to run dhalsim in an ubuntu virtual machine using an arm cpu. When I try to run anytown I get an error:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/36950001/175818195-c3081213-c840-48df-b195-004d9651a125.png">

When I run the `ldd libepanet.so` command on the machine it returns: "Not a dynamic executable"

I also tried running the same command on another ubuntu vm (not using an ARM64 CPU) and it returns a different output: 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/36950001/175818326-c440576c-9841-42a8-a53e-82b08221d654.png">

It seems like the .so file does not support the arm architecture. I think this can bu solved by compiling the orginal code to arm. I would appreciate it, if you can add those. If you decide to support arm, I can also provide a version of your installation script which I used on my system.

**Comment by afmurillo** [comment]
Hello, 

I have fixed the way DHALSIM installs the epynet dependency. Perhaps this will fix the issue that you had. As for the libepanet.so, the file was obtained from Vitens original epynet: https://github.com/Vitens/epynet. Testing DHALSIM in an arm architecture is out of the scope of this project. Nevertheless, in the following weeks all DHALSIM will be ported completely to Python3 and some automatic tests will be updated. Once that happens, it might be easier for the community to contribute to DHALSIM.
